function info = info_type_deblur(type,N,k,eps_rel_k,cond,cardJ,gamma,norm_comp_neg_eig,time)
%
% Type-like definitions for TVdeblur to be used with mxTV software
%
    
    info_type = struct('STATUS',...
  {'EPSILON-OPTIMAL-SOLUTION',...
   'NOT-EPSILON-OPTIMAL-SOLUTION',...
   'MAXIMUM-NUMBER-OF-ITERATIONS-EXCEEDED',...
   'GAMMA_BOUND_TOO_TIGHT'},...
   'NDEBLUR',N,...                  
   'ITERATIONS_K',{k},...
   'EPS_REL_K',{eps_rel_k},...
   'CONDITION_MATRIX',{cond},...
   'CARD_J',{cardJ},...
   'GAMMA',{gamma},...
   'NORM_COMP_NEG_EIG',{norm_comp_neg_eig},...                    
   'TIME',{time});

    info = info_type(type);